"""initial schema

Revision ID: 4ade4331a4c7
Revises: 
Create Date: 2026-03-19 14:50:17.622617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '4ade4331a4c7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('emp_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('department', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sa.Enum('EMPLOYEE', 'MANAGER', 'HR', 'ADMIN', name='role'), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('shift_start_time', sa.Time(), nullable=False),
    sa.Column('shift_end_time', sa.Time(), nullable=False),
    sa.PrimaryKeyConstraint('emp_id')
    )
    op.create_table('attendance_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emp_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=False),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('work_mode', sa.Enum('OFFICE', 'WFH', name='workmode'), nullable=False),
    sa.Column('is_overridden', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['emp_id'], ['employees.emp_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_logs_emp_id'), 'attendance_logs', ['emp_id'], unique=False)
    op.create_index(op.f('ix_attendance_logs_timestamp'), 'attendance_logs', ['timestamp'], unique=False)
    op.create_table('authenticators',
    sa.Column('credential_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('emp_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('public_key', sa.LargeBinary(), nullable=False),
    sa.Column('sign_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['emp_id'], ['employees.emp_id'], ),
    sa.PrimaryKeyConstraint('credential_id')
    )
    op.create_table('daily_attendance_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emp_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('first_clock_in', sa.DateTime(), nullable=True),
    sa.Column('last_clock_out', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('NORMAL', 'LATE', 'EARLY_LEAVE', 'ABNORMAL', name='attendancestatus'), nullable=False),
    sa.ForeignKeyConstraint(['emp_id'], ['employees.emp_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('emp_id', 'date', name='uq_summary_emp_date')
    )
    op.create_table('system_config',
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['employees.emp_id'], ),
    sa.PrimaryKeyConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_config')
    op.drop_table('daily_attendance_summaries')
    op.drop_table('authenticators')
    op.drop_index(op.f('ix_attendance_logs_timestamp'), table_name='attendance_logs')
    op.drop_index(op.f('ix_attendance_logs_emp_id'), table_name='attendance_logs')
    op.drop_table('attendance_logs')
    op.drop_table('employees')
    # ### end Alembic commands ###
